### ISSUE TITLE
Windows 10 build 14316 - RDP auth error

### ISSUE THREAD

**Issue by MilanDasek** [kmscode/mRemote3G#55]
Hi,

I am getting an error on latest build of Windows 10 build 14316 (I've upgraded from standard build) when trying connect using RDP - An authentication error has occurred (Code: 0x80004005).

I've tried to install mRemote3G from scratch, but did not help. After first start I get an error - An authentication error has occurred. The Local Security Authority cannot be contacted. Then - An authentication error has occurred (Code: 0x80004005).

When I start RDP (standard tool) from Windows, connections work fine to all servers.

mRemote3G version - 1.94.2.34463

Any ideas?

**Comment by MilanDasek** [comment]
log file

2016-04-11 07:08:12,288 [1] INFO - mRemote3G 1.94.2.34463 starting.
2016-04-11 07:08:12,297 [1] INFO - Command Line: C:\Program Files (x86)\mRemote3G\mRemote3G.exe
2016-04-11 07:08:13,663 [1] INFO - Microsoft Windows 10 Pro Insider Preview 64-bit
2016-04-11 07:08:13,664 [1] INFO - Microsoft .NET CLR 4.0.30319.42000
2016-04-11 07:08:13,664 [1] INFO - System Culture: en-US/English (United States)
2016-04-11 07:08:15,771 [1] WARN - XmingPortablePuttySessions.Watcher.StartWatching() failed.
System.ArgumentException: The directory name sessions is invalid.
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at mRemoteNG.Config.Putty.XmingProvider.StartWatcher() in d:\Source\mRemoteNG\mRemoteV1\Config\Putty\XmingProvider.vb:line 104
2016-04-11 07:08:18,331 [1] INFO - Setting Console switch for RDC 10.0.14316.
2016-04-11 07:08:18,335 [1] INFO - RD Gateway is supported.
2016-04-11 07:08:21,676 [1] INFO - Protocol Event Disconnected.
Message:
1287

2016-04-11 07:08:21,676 [1] WARN - RDP disconnected!


Error code 1287.
2016-04-11 07:08:21,716 [7] INFO - Connection Event Closed
2016-04-11 07:08:21,716 [7] INFO - Connection to %HOST% via RDP closed by user PC\user.
2016-04-11 07:08:25,509 [1] INFO - Setting Console switch for RDC 10.0.14316.
2016-04-11 07:08:25,509 [1] INFO - RD Gateway is supported.
2016-04-11 07:08:26,956 [1] INFO - Protocol Event Disconnected.
Message:
1287

2016-04-11 07:08:26,957 [1] WARN - RDP disconnected!


Error code 1287.
2016-04-11 07:08:26,980 [6] INFO - Connection Event Closed
2016-04-11 07:08:26,980 [6] INFO - Connection to %HOST% via RDP closed by user PC\user.

**Comment by Whatsek** [comment]
This is an Windows 10 bug, should be fixed in the next build. In the meantime, you can set: Use credSSP = No, in the connection settings, if the target server supports that.

**Comment by kmscode** [comment]
@Whatsek - Thanks for the assistance. Any documentation or additional references to this being a Windows bug?

**Comment by MilanDasek** [comment]
Ah thanks. Let's hope they fix it asap. Thanks for credSSP (NLA) tip - works!
